/* DO NOT EDIT THIS FILE */

/**
 *
 * @type {({date: string, comments: [{author: string, message: string}], author: string, title: string, body: [string], tags: [string]})[]}
 */
let INPUT_JSON = [
    {
        title: "Alice's Adventures in Wonderland",
        author: "Lewis Carroll",
        date: "1985-11-26",
        body: [
            "Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, ‘and what is the use of a book,’ thought Alice ‘without pictures or conversations?’",
            "So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.",
            "There was nothing so VERY remarkable in that; nor did Alice think it so VERY much out of the way to hear the Rabbit say to itself, ‘Oh dear! Oh dear! I shall be late!’ (when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually TOOK A WATCH OUT OF ITS WAISTCOAT-POCKET, and looked at it, and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket, or a watch to take out of it, and burning with curiosity, she ran across the field after it, and fortunately was just in time to see it pop down a large rabbit-hole under the hedge."
        ],
        comments: [
            {
                author: "Bob Dole",
                message: "Loved it!"
            },
            {
                author: "Jimmy Carter",
                message: "What's up with the rabbit? Why can't he stay on time!"
            }
        ]
    },
    /* DO NOT EDIT THIS FILE */
    {
        title: "Don Quixote",
        author: "Miguel de Cervantes",
        date: "1605-01-01",
        body: [
            "In a village of La Mancha, the name of which I have no desire to call to mind, there lived not long since one of those gentlemen that keep a lance in the lance-rack, an old buckler, a lean hack, and a greyhound for coursing. An olla of rather more beef than mutton, a salad on most nights, scraps on Saturdays, lentils on Fridays, and a pigeon or so extra on Sundays, made away with three-quarters of his income. The rest of it went in a doublet of fine cloth and velvet breeches and shoes to match for holidays, while on week-days he made a brave figure in his best homespun. He had in his house a housekeeper past forty, a niece under twenty, and a lad for the field and market-place, who used to saddle the hack as well as handle the bill-hook. The age of this gentleman of ours was bordering on fifty; he was of a hardy habit, spare, gaunt-featured, a very early riser and a great sportsman. They will have it his surname was Quixada or Quesada (for here there is some difference of opinion among the authors who write on the subject), although from reasonable conjectures it seems plain that he was called Quexana. This, however, is of but little importance to our tale; it will be enough not to stray a hair’s breadth from the truth in the telling of it.",
            "You must know, then, that the above-named gentleman whenever he was at leisure (which was mostly all the year round) gave himself up to reading books of chivalry with such ardour and avidity that he almost entirely neglected the pursuit of his field-sports, and even the management of his property; and to such a pitch did his eagerness and infatuation go that he sold many an acre of tillageland to buy books of chivalry to read, and brought home as many of them as he could get. But of all there were none he liked so well as those of the famous Feliciano de Silva’s composition, for their lucidity of style and complicated conceits were as pearls in his sight, particularly when in his reading he came upon courtships and cartels, where he often found passages like “the reason of the unreason with which my reason is afflicted so weakens my reason that with reason I murmur at your beauty;” or again, “the high heavens, that of your divinity divinely fortify you with the stars, render you deserving of the desert your greatness deserves.” Over conceits of this sort the poor gentleman lost his wits, and used to lie awake striving to understand them and worm the meaning out of them; what Aristotle himself could not have made out or extracted had he come to life again for that special purpose. He was not at all easy about the wounds which Don Belianis gave and took, because it seemed to him that, great as were the surgeons who had cured him, he must have had his face and body covered all over with seams and scars. He commended, however, the author’s way of ending his book with the promise of that interminable adventure, and many a time was he tempted to take up his pen and finish it properly as is there proposed, which no doubt he would have done, and made a successful piece of work of it too, had not greater and more absorbing thoughts prevented him."
        ],
        comments: [
            {
                author: "Terry Gilliam",
                message: "Very pythonic, glad I made this into a film"
            }
        ]
    },
    /* DO NOT EDIT THIS FILE */
    {
        title: "Merry Tales",
        author: "Mark Twain",
        date: "1892-01-01",
        body: [
            "You have heard from a great many people who did something in the war; is it not fair and right that you listen a little moment to one who started out to do something in it, but didn’t? Thousands entered the war, got just a taste of it, and then stepped out again, permanently. These, by their very numbers, are respectable, and are therefore entitled to a sort of voice,—not a loud one, but a modest one; not a boastful one, but an apologetic one. They ought not to be allowed much space among better people—people who did something—I grant that; but they ought at least to be allowed to state why they didn’t do anything, and also to explain the process by which they didn’t do anything. Surely this kind of light must have a sort of value.",
            "Out West there was a good deal of confusion in men’s minds during the first months of the great trouble—a good deal of unsettledness, of leaning first this way, then that, then the other way. It was hard for us to get our bearings. I call to mind an instance of this. I was piloting on the Mississippi when the news came that South Carolina had gone out of the Union on the 20th of December, 1860. My pilot-mate was a New Yorker. He was strong for the Union; so was I. But he would not listen to me with any patience; my loyalty was smirched, to his eye, because my father had owned slaves. I said, in palliation of this dark fact, that I had heard my father say, some years before he died, that slavery was a great wrong, and that he would free the solitary negro he then owned if he could think it right to give away the property of the family when he was so straitened in means. My mate retorted that a mere impulse was nothing—anybody could pretend to a good impulse; and went on decrying my Unionism and libeling my ancestry. A month later the secession atmosphere 11had considerably thickened on the Lower Mississippi, and I became a rebel; so did he. We were together in New Orleans, the 26th of January, when Louisiana went out of the Union. He did his full share of the rebel shouting, but was bitterly opposed to letting me do mine. He said that I came of bad stock—of a father who had been willing to set slaves free. In the following summer he was piloting a Federal gun-boat and shouting for the Union again, and I was in the Confederate army. I held his note for some borrowed money. He was one of the most upright men I ever knew; but he repudiated that note without hesitation, because I was a rebel, and the son of a man who owned slaves.",
            "In that summer—of 1861—the first wash of the wave of war broke upon the shores of Missouri. Our State was invaded by the Union forces. They took possession of St. Louis, Jefferson Barracks, and some other points. The Governor, Claib Jackson, issued his proclamation calling out fifty thousand militia to repel the invader."
        ],
        comments: []
    },
    /* DO NOT EDIT THIS FILE */
    {
        title: "Pride and Prejudice",
        author: "Jane Austen",
        date: "1813-01-28",
        body: [
            "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
            "However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters."
        ],
        comments: [
            {
                author: "Mrs Bennet",
                message: "Oh Mr Darcy!"
            },
            {
                author: "Lydia",
                message: "Why did we choose this title?"
            }
        ]
    }
];
/* DO NOT EDIT THIS FILE */